### ISSUE TITLE
./shared.js not found

### ISSUE THREAD

**Issue by openafox** [remcohaszing/remark-mermaidjs#16]
Thanks for the recent update!!  Sadly something broke in the build and shared.js is not being included in node_modules/remark-mermaidjs:

![image](https://user-images.githubusercontent.com/11250430/205711859-8e18b470-f89b-4824-8131-2a1107fa1920.png)

**Comment by remcohaszing** [comment]
Thanks for the report! I know what causes this, but I'm currently not on my laptop. I'll fix in in an hour or so.

**Comment by remcohaszing** [comment]
Fixed in version 4.1.1.
