### ISSUE TITLE
Puppeteer brokens at 4.1.1

### ISSUE THREAD

**Issue by KimPinot** [remcohaszing/remark-mermaidjs#18]
Hello.
I'm using remark-mermaidjs@4.1.1 with unifiedjs.
When I enter page it includes mermaid chart, This error has shown.
```
./node_modules/puppeteer-core/lib/esm/puppeteer/common/IsolatedWorld.js
Attempted import error: 'source' is not exported from '../generated/injected.js' (imported as 'injectedSource').
```

I think this error must be from puppeteer, But I want to know anyone has same issue

```js
return unified()
    .use(RemarkParse, {})
    .use(RemarkMermaidjs, {
      launchOptions: {},
    })
    .process(markdown);
```

**Comment by remcohaszing** [comment]
I can’t reproduce this by updating dependencies, but if this issue exists, it’s an issue in `puppeteer-core`.
