### ISSUE TITLE
Using this plugin with rehypeSanitize

### ISSUE THREAD

**Issue by marekvospel** [remcohaszing/remark-mermaidjs#19]
Hello, I'm trying to set this plugin up with sanitization, because I am working with user input, so I have to prevent XSS. For sanitization I'm trying to use rehype-sanitize and when using this plugin, the svg elements are removed and the style tag gets converted into a paragraph, so the style rules are visible.

![image](https://user-images.githubusercontent.com/73162071/213487620-a3f77f6e-82c5-4fac-b6b1-22781e7b1d43.png)

What options do I need to pass to this plugin / in mermaid.initialize or to rehype-sanitize for this plugin to work? (It would be nice if usage examples for this plugin were added to readme)

My remark / rehype looks like this:
```js
mermaid.initialize()
const result = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkMermaid)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeRaw)
    .use(rehypeSanitize)
    .use(rehypeStringify, {
      allowDangerousHtml: true,
      allowDangerousCharacters: true,
    })
    .process(markdown)
```

**Comment by wooorm** [comment]
@remcohaszing Good reason to make this a rehype plugin instead, so it can be used *after* sanitizing.

**Comment by remcohaszing** [comment]
You will need to pass options to `rehype-sanitize` for this, but unfortunately I don’t know what options.

@wooorm yes! I also considered a rehype plugin would probably be a better fit, but only long after I created this plugin.

I do think users can pass some malicious options in mermaid diagrams though, so maybe sanitization isn’t a bad idea?

**Comment by remcohaszing** [comment]
I’m closing this issue, as it’s not actionable from the `remark-mermaidjs` repository. I do welcome anyone to figure out the needed `rehype-sanitize` and share them here.

**Comment by wooorm** [comment]
It’s going to be like 1000s of lines of custom rules in `rehype-sanitize`. Allowing those rules is going to open up XSS attacks, so it’s a terrible idea anyway.
The only way to do have user content with mermaid like this, is to not trust this stuff with rehype-sanitize, and then to use a rehype version of this plugin
