### ISSUE TITLE
mermaidjs with the react-markdown return TypeError

### ISSUE THREAD

**Issue by angelinekwan** [remcohaszing/remark-mermaidjs#20]
I tried to use the mermaidjs with the [react-markdown](https://github.com/remarkjs/react-markdown) for a [Remix app](https://remix.run/). However, my app stop working with error

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at Object.<anonymous> (/my-app/node_modules/remark-mermaidjs/index.js:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /my-app/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/my-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/my-app/node_modules/express/lib/router/route.js:144:13)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
```

**package.json**
```
"react-markdown": "^8.0.3",
"remark-mermaidjs": "^4.1.1",
```

I also have a list of rehype and remark that has no issue running with react-markdown
```
"rehype-sanitize": "^5.0.1",
"rehype-slug": "^5.0.1",
"remark-breaks": "^3.0.2",
"remark-directive": "^2.0.1",
"remark-directive-rehype": "^0.4.0",
"remark-gfm": "^3.0.1",
"remark-remove-comments": "^0.2.0",
```

**component.tsx**
```
import React from "react";

import ReactMarkdown from "react-markdown";
import remarkMermaid from "remark-mermaidjs";

import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import remarkDirective from "remark-directive";
import remarkDirectiveRehype from "remark-directive-rehype";
import remarkRemoveComments from "remark-remove-comments";
import remarkBreaks from "remark-breaks";

interface Props {
	content: string;
}

export function MarkDown({ content }: Props) {
	return (
        <ReactMarkdown
            components={{
                p: ({ children }) => {
                    return (
                        <p>
                            {children}
                        </p>
                    );
                },
            }}
            children={content}
            rehypePlugins={[rehypeSlug]}
            remarkPlugins={[
                remarkBreaks,
                remarkGfm,
                remarkDirective,
                remarkDirectiveRehype,
                remarkRemoveComments,
                remarkMermaid,
            ]}
        />
	);
}
```

**Content in markdown**

```
## Heading 2
Paragraph lorem ipsum
```

<img width="177" alt="Screenshot 2023-02-27 at 14 35 12" src="https://user-images.githubusercontent.com/3796599/221565313-499d6482-4e5a-4f22-b284-36c431a6a38f.png">

**Comment by remcohaszing** [comment]
The error appears on this line:

https://github.com/remcohaszing/remark-mermaidjs/blob/95188b1a1466f1e16b057426562e0b99a8c26c90/index.ts#L15

This line uses `import.meta.url`, which is defined in ESM, but appears to be undefined for you. This is probably caused by an incorrect transpilation to CJS.

This is a bug in Remix, not `remark-mermaidjs`. Some possibilities I see for them to fix it are:

- Support ESM. (This is definitely preferred!)
- Replace `import.meta.url` with `String(pathToFileURL(__filename))`
- Replace `createRequire(import.meta.url)` with `require`

**Comment by angelinekwan** [comment]
@remcohaszing Thanks for the insights. 

Are you referring to this Remix issue [Unable to import from libs using ESM](https://github.com/remix-run/remix/issues/109). Remix has a work around for importing [ESM packages](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages), that I have applied for react-markdown, rehype* and remark* packages. If I don't, it will show in the console in development mode. However, it was not the case with `remark-mermaidjs`

```
[1] rehype-slug is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
[1] remark-gfm is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
[1] remark-directive is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
[1] remark-directive-rehype is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
[1] remark-breaks is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.

```

**Comment by remcohaszing** [comment]
Yes, that is the issue where they attempted to solve it. They just didn’t solve it for the specific use case of `import.meta.url`. You should create a new issue there (if it doesn’t exist yet).

**Comment by angelinekwan** [comment]
There is this [discussion](https://github.com/remix-run/remix/discussions/2607) about support `import.meta.url`.
Is there any alternative that I could work on in my end? 
Probably to use shortcode in markdown to call for a react mermaidjs component instead of using remark...

**Comment by remcohaszing** [comment]
That discussion is old. Maybe if you create a new issue about being unable to use ESM packages, with a link to this particular issue, they will take it more seriously. Yours is a very legitimate, practical use case they should support IMO.

As a workaround, ff you can move it to an async context, you can try a dynamic import.

Otherwise, maybe, as a very last resort this works:

```ts
function cjsRemarkMermaid(options) {
  return async (ast, file) => {
    const { default: remarkMermaid } = await import('remark-mermaidjs')
    const transformer = remarkMermaid.call(this, options)
    return transformer.call(this, ast, file)
  }
}

module.exports = cjsRemarkMermaid
```

**Comment by angelinekwan** [comment]
@remcohaszing I created a [Remix issue #5588](https://github.com/remix-run/remix/issues/5588) -> If you think there is something missing or incorrect feel free to comment 🙏 

I tried your suggested alternative by creating the following -> I might have misunderstood how to use it:

```
// esm.modules.js
function cjsRemarkMermaid(options) {
  return async (ast, file) => {
    const { default: remarkMermaid } = await import('remark-mermaidjs')
    const transformer = remarkMermaid.call(this, options)
    return transformer.call(this, ast, file)
  }
}

module.exports = cjsRemarkMermaid
```

```
// component.tsx
import ReactMarkdown from "react-markdown";
import cjsRemarkMermaid from "../../esm-modules.js;

interface Props {
	content: string;
}

export function MarkDown({ content }: Props) {
	return (
        <ReactMarkdown
            components={{
                p: ({ children }) => {
                    return (
                        <p>
                            {children}
                        </p>
                    );
                },
            }}
            children={content}
            remarkPlugins={[
                cjsRemarkMermaid,
            ]}
        />
	);
}
```

But the app crash with the additional error:
Probably because `react-markdown` currently expects all plugins to be [syncronous](https://github.com/remarkjs/react-markdown/blob/8ed18dafa8de638ab72a8db29f156f9fd9cf9e2e/src/react-markdown.js#L119)

```
Error: `runSync` finished async. Use `run` instead
    at assertDone (/my-app/node_modules/react-markdown/node_modules/unified/lib/index.js:566:11)
    at Function.runSync (/my-app/node_modules/react-markdown/node_modules/unified/lib/index.js:352:5)
    at ReactMarkdown (/my-app/node_modules/react-markdown/lib/react-markdown.js:106:30)
    at processChild (/my-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/my-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/my-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/my-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/my-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at handleRequest (/my-app/app/entry.server.tsx:30:17)
    at handleDocumentRequest (/my-app/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:395:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at requestHandler (/my-app/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:49:18)
    at /my-app/node_modules/@remix-run/express/dist/server.js:39:22
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at node_modules/remark-mermaidjs/index.js (/my-app/node_modules/remark-mermaidjs/index.js:8:11)
    at /my-app/build/index.js:7:56
    at /my-app/esm-modules.js:3:46
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /my-app/esm-modules.js:3:40
fatal error: all goroutines are asleep - deadlock!
```

**Comment by remcohaszing** [comment]
Oof that’s a tough one. I’m not sure how to proceed here.

`remark-mermaidjs` is an asynchronous plugin. I don’t see how it can be synchronous. To solve this, `react-markdown` would need to support asynchronous plugins, **and** it would need to work with Remix, **and** it would need to work with other React frameworks.

Do you **need** to use a `content` prop? Can you use MDX? (MDX can also handle plain markdown files and use all of remark / rehype)

**Comment by angelinekwan** [comment]
> Do you need to use a content prop?

The content of the markdown comes from a field that editor add content in the Sanity CMS.
```
## Heading
Paragraph lorem ipsum
... mermaid code
```

**Comment by remcohaszing** [comment]
I know Remix supports MDX, but I don't know how they support it. I haven't used Remix nor Sanity CMS myself.

I'm afraid I can't help you any further. I hope you find a solution and are willing to share it here to help others who might run into this.

**Comment by angelinekwan** [comment]
Going with MDX approach by using shortcode in markdown to render `mermaid component` using [remark-directive](https://www.npmjs.com/package/remark-directive) and [remark-directive-rehype](https://www.npmjs.com/package/remark-directive-rehype/v/0.3.0) packages.

```
// markdown.tsx
import React from "react";
import ReactMarkdown from "react-markdown";
import remarkDirective from "remark-directive";
import remarkDirectiveRehype from "remark-directive-rehype";

import { Mermaid } from "~/components/mermaid";

declare global {
	namespace JSX {
		interface IntrinsicElements {
			mermaid: { id: string; children: string };
		}
	}
}

interface Props {
	content: string;
}

export function MarkDown({ content }: Props) {
	return (
        <ReactMarkdown
            components={{
                mermaid: Mermaid,
            }}
            children={content}
            remarkPlugins={[
                remarkDirective,
                remarkDirectiveRehype,
            ]}
        />
	);
}
```

```
// components/mermaid.tsx
import React from "react";
import mermaid from "mermaid";

// Set default configuration for Mermaid
mermaid.initialize({
  startOnLoad: true,
});

type MermaidProps = {
  children: string;
  id?: string;
};

export function Mermaid({
  children,
  id,
}: MermaidProps) {
  //const randomId = generateRandomId();

  React.useEffect(() => {
    mermaid.init(undefined, `#mermaid-${id}`);
  }, []);
  
  if (!children) return null;

  return <div id={`mermaid-${id}`}>{children}</div>;
};
```

Importing ESM package to Remix - [guide](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages)
```
//remix.config.js
module.exports = {
	serverDependenciesToBundle: [
		/^rehype.*/,
		/^remark.*/,
		/^react-markdown$/,
		/^mermaid.*/,
		/^khroma*/,
		/^d3*/,
		/^lodash-es*/,
		/^dagre-d3-es.*/,
		/^robust-predicates*/,
		/^internmap.*/,
	],
};

```

Shortcode in markdown
`::mermaid[flowchart TD;Start-->Stop;]{id="1"}
`
<img width="121" alt="Screenshot 2023-02-28 at 15 34 28" src="https://user-images.githubusercontent.com/3796599/221869428-775464be-47e1-4b5c-a354-fe77fb9f9821.png">

This approach works but if there are more mermaid diagram in the same page, some of the diagram didn't get render with the following error, probably due to the mermaid script loads as async.

<img width="1448" alt="Screenshot 2023-02-28 at 15 35 32" src="https://user-images.githubusercontent.com/3796599/221869731-d2f77c48-e6a8-47d2-a6c7-5ffe71c18edd.png">

**Comment by remcohaszing** [comment]
It looks like you went from server-side rendering to client-side rendering. This is also supported by `remark-mermaidjs`, and is even synchronous.

**Comment by wooorm** [comment]
uhh, I don’t think that’s an “MDX approach”? Where is MDX?

**Comment by angelinekwan** [comment]
What i meant is include JSX in Markdown document

**Comment by remcohaszing** [comment]
> Do you have an example how it would work in my example setup?

The same as in your original example. I don’t know how Remix determines what to run on the server or client. Your original post showed a Node.js stacktrace, which means it runs on the server. Your latest examples shows you import mermaid, which only works client-side.

**Comment by angelinekwan** [comment]
Is tricky with the Remix setup.
Sometime or some of the diagram didn't get render with the following error, probably due to Remix to bundle the ESM module directly into the server build instead of requiring it at runtime causing the text node not matching between server and client side.

The same component works with basic react component - code [example](https://codesandbox.io/s/react-with-mermaid-forked-4bly62?file=/src/index.js).
