### ISSUE TITLE
Question: how to set theme when used in React

### ISSUE THREAD

**Issue by humphd** [remcohaszing/remark-mermaidjs#21]
I'm using `remark-mermaidjs` with `react-markdown` in the browser, and it's fantastic, thank you!

In your docs and code, you mention about calling `mermaid.initialize()` manually to set things like the `theme` or other `mermaidOptions`.  I'm trying to figure out how to do this, but can't get it to work.  I wonder if you could give a hint.

Essentially my code is doing:

```tsx
import ReactMarkdown from "react-markdown";
import remarkMermaid from "remark-mermaidjs";
import remarkGfm from "remark-gfm";
...
    <ReactMarkdown
      className="message-text"
      children={children}
      remarkPlugins={[remarkGfm, remarkMermaid]}
    />
```

How can I set `mermaidOptions` here?

**Comment by remcohaszing** [comment]
It's really cool to hear you like it!

You can set the mermaid options using their `initialize` function.

```js
import mermaid from 'mermaid'

mermaid.initialize(mermaidOptions)
```

Note that `remark-mermaidjs` uses Mermaid 9, but the latest version is 10. You should make sure you only have one version of Mermaid in your dependency tree.

Also I'm working on a new version with many improvements. I'll probably release it this week, aiming for tomorrow.

**Comment by humphd** [comment]
That's great, thanks!  I'll watch out for your update.
