### ISSUE TITLE
Module not found in NextJS

### ISSUE THREAD

**Issue by freyandhy** [remcohaszing/remark-mermaidjs#22]
![CleanShot 2023-08-24 at 10 12 26](https://github.com/remcohaszing/remark-mermaidjs/assets/12264875/33bd9267-044e-4b33-9a55-f5336f8f0964)

I try to use `remark-mermaidjs` at my NextJS app but always have an error `Module not found`.
I use `"remark-mermaidjs": "^5.0.1"` and `"next": "13.4.12"`

**Comment by remcohaszing** [comment]
You can use remark in various ways in a Next.js project. Could you create a minimal reproduction?

Also, why are you using `remark-mermaidjs` instead of [`rehype-mermaidjs`](https://github.com/remcohaszing/rehype-mermaidjs)?

**Comment by remcohaszing** [comment]
I found the issue, but it's late. I will fix this tomorrow.
