### ISSUE TITLE
 Inconsistent Rendering Results in Mermaid

### ISSUE THREAD

**Issue by XIYO** [remcohaszing/remark-mermaidjs#26]
Hello,

I'm using Remark Mermaid in Svelte, and I've encountered a slight issue.

Similar to React, Svelte goes through a hydration process where it renders once more on the client-side. During this process, the Mermaid output differs between the server and client, causing elements to disappear in the browser.

The solution appears to be quite straightforward: simply render the content on the server-side to prevent hydration issues. However, in the pursuit of precision, I've raised this issue. Why does the output differ between the server and client when we enable hydration?

![img](https://github.com/user-attachments/assets/23cf454d-2ca1-4009-a353-2f46c4c696e7)

https://github.com/XIYO/svelte-hole/tree/master/remark-mermaidjs-hole

**Comment by XIYO** [comment]
Oops..... 🤦‍♀️
Was it simply a matter of using rehypeMermaid all along? 🙈

**Comment by XIYO** [comment]
I understand the operating principle now.
Mermaid itself is browser-dependent, so it's not a suitable tool for the hydration stage."

**Comment by remcohaszing** [comment]
Also you should use [`rehype-mermaid`](https://github.com/remcohaszing/rehype-mermaid) instead.
