### ISSUE TITLE
Suggestions to make it work on Vercel?

### ISSUE THREAD

**Issue by CristhianMotoche** [remcohaszing/remark-mermaidjs#27]
Hello there! I was wondering if you have any suggestions to use this plugin on a build environment like the one of Vercel. I installed a browser with `playwright install chromium-headless-shell` but when it tries to launch the browser it fails with:

```
[Error: [next-mdx-remote] error compiling MDX:
browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     npx playwright install-deps                      ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libnss3\                         ║
║         libnspr4\                                    ║
║         libgbm1                                      ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
```

So, I tried to install it with deps `playwright install --with-deps chromium-headless-shell` but it fails with:

```
Error: Error installing playwright: Error: Command failed: playwright install --with-deps chromium-headless-shell
BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.
sh: line 1: apt-get: command not found
 Installing dependencies...
Failed to install browsers
Error: Installation process exited with code: 127
 BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.
sh: line 1: apt-get: command not found
```

FWIW, I'm using `next-mdx-remote/serialize` and using this plugin like this:

```ts
    const source = await serialize(
      mdx,
      {
        mdxOptions: {
          remarkPlugins: [
            ..., // plugins
            [remarkMermaid],
            ... // more plugins
         }
      }
    );
```

Thanks in advance for any suggestions on this ✌️

**Comment by remcohaszing** [comment]
1. Why are you using this package? From the readme:
> \[!IMPORTANT]
>
> Use cases for this package are rare. You should probably use [`rehype-mermaid`](https://github.com/remcohaszing/rehype-mermaid) instead.

However, you’ll run into the same issue with `rehype-mermaid`.

2. I don’t know the `chromium-headless-shell` browser for Playwright. Maybe just use `chromium`?
3. The error clearly states you’re using an unsupported OS. Use a different OS.
4. Why are you using `next-mdx-remote`? That only complicates things. I strongly recommend using `@next/mdx`.

**Comment by CristhianMotoche** [comment]
Thanks @remcohaszing !
