### ISSUE TITLE
Option to render without Puppeteer/Playwright

### ISSUE THREAD

**Issue by ChristianMurphy** [remcohaszing/remark-mermaidjs#3]
Currently this plugin makes the assumption that it will be run in Node, with the ability to start a new browser process to do rendering.
Non-Node environments, like browsers and deno, may have limited ability to do this.
It may be good to explore alternative rendering methods for these environments.

**Comment by remcohaszing** [comment]
Ideally I would like to use jsdom, but [several issues on mermaidjs](https://github.com/mermaid-js/mermaid/issues?q=is:issue+jsdom) state that doesn’t work.

I like the idea of using different rendering methods. Browsers could just invoke mermaidjs directly.

**Comment by ChristianMurphy** [comment]
Another possibility would be porting part of the engine, something @wooorm seems to be looking into https://github.com/remarkjs/remark/discussions/932#discussioncomment-1963252

**Comment by ChristianMurphy** [comment]
[HappyDom](https://github.com/capricorn86/happy-dom) could be another alternative to JSDOM

**Comment by remcohaszing** [comment]
HappyDom looks interesting. I wonder if it doesn’t have the same issues as JSDOM.

**Comment by wooorm** [comment]
note that GH renders them in browsers: https://github.com/EddieHubCommunity/LinkFree/discussions/1087

**Comment by remcohaszing** [comment]
I just gave HappyDom a try, but it doesn’t work. I used the following script:

```js
import { readFile } from 'fs/promises';
import { createRequire } from 'module';

import { Window } from 'happy-dom';

const require = createRequire(import.meta.url);

const window = new Window();
const script = await readFile(require.resolve('mermaid/dist/mermaid.min.js'), 'utf8');
window.eval(script);
window.mermaid.initialize({ theme: 'base' });
const result = window.mermaid.render(
  'a',
  `
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
`,
);
console.log(result);
```

It throws the following when calling `window.mermaid.render`:

```js
TypeError: s.node(...).getBBox is not a function
    at t.exports (evalmachine.<anonymous>:2:800831)
    at HTMLUnknownElement.<anonymous> (evalmachine.<anonymous>:2:795021)
    at nl.each (evalmachine.<anonymous>:2:335280)
    at t.exports (evalmachine.<anonymous>:2:794936)
    at g (evalmachine.<anonymous>:2:803806)
    at ok (evalmachine.<anonymous>:2:624665)
    at Object.render (evalmachine.<anonymous>:2:777823)
    at file:///home/remco/Projects/remark-mermaidjs/script.mjs:12:31
```

**Comment by remcohaszing** [comment]
I’m closing this issue, because this requires upstream changes in mermaid that I don’t expect to see anytime soon.

If someone finds a solution, I would love to hear about it.
